import { minify, Options } from 'html-minifier-terser';

const htmlMinifierOptions: Options = {
  caseSensitive: true,
  collapseBooleanAttributes: true,
  collapseWhitespace: true,
  collapseInlineTagWhitespace: true,
  conservativeCollapse: true,
  decodeEntities: true,
  html5: true,
  ignoreCustomComments: [],
  ignoreCustomFragments: [/{{[\S\s]*?}}/, /{%[\S\s]*?%}/],
  includeAutoGeneratedTags: true,
  keepClosingSlash: false,
  maxLineLength: 1000,
  minifyCSS: true,
  minifyJS: true,
  minifyURLs: true,
  noNewlinesBeforeTagClose: true,
  preserveLineBreaks: true,
  preventAttributesEscaping: false,
  processConditionalComments: false,
  processScripts: [],
  quoteCharacter: '"',
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: true,
  removeEmptyElements: false,
  removeOptionalTags: false,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: false,
  removeStyleLinkTypeAttributes: false,
  removeTagWhitespace: false,
  sortAttributes: false,
  sortClassName: false,
  trimCustomFragments: false,
  useShortDoctype: false
};

export async function minifyHTML(html: string): Promise<string> {
  return minify(html, htmlMinifierOptions);
}
